version: '2'
services:
  nginx:
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    links:
      - php-fpm
  php-fpm:
    build:
      context: ./
      dockerfile: docker/php-fpm/Dockerfile
    volumes:
      - ./:/var/www
    links:
      - db
     # - redis
    environment:
      - DB_PORT=5432
      - DB_HOST=db
     # - REDIS_PORT=6379
     # - REDIS_HOST=redis
  php-cli:
    build:
      context: ./
      dockerfile: docker/php-cli/Dockerfile
    volumes:
      - ./:/var/www
    links:
      - db
    #  - redis
    environment:
      - DB_PORT=5423
      - DB_HOST=db
     # - REDIS_PORT=6379
    #  - REDIS_HOST=redis
    tty: true
  db:
    image: postgres:11.2
    volumes:
      - ./docker/postgres/:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
  #redis:
   # image: redis:5.0
    #ports:
     # - "63791:6379"